/**
 * BulkUpdateRequest automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.airtable;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class BulkUpdateRequest {
    private List<String> performUpsert;
    private Boolean returnFieldsByFieldId;
    private Boolean typecast;
    private List<Record> records;
    @JsonSetter("performUpsert")
    public void setPerformUpsert(List<String> performUpsert) {
        this.performUpsert = performUpsert;
    }
    @JsonGetter("performUpsert")
    public List<String> getPerformUpsert() {
        return this.performUpsert;
    }
    @JsonSetter("returnFieldsByFieldId")
    public void setReturnFieldsByFieldId(Boolean returnFieldsByFieldId) {
        this.returnFieldsByFieldId = returnFieldsByFieldId;
    }
    @JsonGetter("returnFieldsByFieldId")
    public Boolean getReturnFieldsByFieldId() {
        return this.returnFieldsByFieldId;
    }
    @JsonSetter("typecast")
    public void setTypecast(Boolean typecast) {
        this.typecast = typecast;
    }
    @JsonGetter("typecast")
    public Boolean getTypecast() {
        return this.typecast;
    }
    @JsonSetter("records")
    public void setRecords(List<Record> records) {
        this.records = records;
    }
    @JsonGetter("records")
    public List<Record> getRecords() {
        return this.records;
    }
}
