/**
 * BulkUpdateResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.airtable;

import com.fasterxml.jackson.annotation.*;

public class BulkUpdateResponse {
    private java.util.List<String> createdRecords;
    private java.util.List<String> updatedRecords;
    private java.util.List<Record> records;

    @JsonSetter("createdRecords")
    public void setCreatedRecords(java.util.List<String> createdRecords) {
        this.createdRecords = createdRecords;
    }

    @JsonGetter("createdRecords")
    public java.util.List<String> getCreatedRecords() {
        return this.createdRecords;
    }

    @JsonSetter("updatedRecords")
    public void setUpdatedRecords(java.util.List<String> updatedRecords) {
        this.updatedRecords = updatedRecords;
    }

    @JsonGetter("updatedRecords")
    public java.util.List<String> getUpdatedRecords() {
        return this.updatedRecords;
    }

    @JsonSetter("records")
    public void setRecords(java.util.List<Record> records) {
        this.records = records;
    }

    @JsonGetter("records")
    public java.util.List<Record> getRecords() {
        return this.records;
    }
}

