/**
 * BulkUpdateResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.airtable;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class BulkUpdateResponse {
    private List<String> createdRecords;
    private List<String> updatedRecords;
    private List<Record> records;
    @JsonSetter("createdRecords")
    public void setCreatedRecords(List<String> createdRecords) {
        this.createdRecords = createdRecords;
    }
    @JsonGetter("createdRecords")
    public List<String> getCreatedRecords() {
        return this.createdRecords;
    }
    @JsonSetter("updatedRecords")
    public void setUpdatedRecords(List<String> updatedRecords) {
        this.updatedRecords = updatedRecords;
    }
    @JsonGetter("updatedRecords")
    public List<String> getUpdatedRecords() {
        return this.updatedRecords;
    }
    @JsonSetter("records")
    public void setRecords(List<Record> records) {
        this.records = records;
    }
    @JsonGetter("records")
    public List<Record> getRecords() {
        return this.records;
    }
}
