/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.airtable;

import app.sdkgen.client.ClientAbstract;
import app.sdkgen.client.Credentials.*;
import app.sdkgen.client.CredentialsInterface;
import app.sdkgen.client.Exception.Authenticator.InvalidCredentialsException;
import app.sdkgen.client.Exception.ClientException;
import app.sdkgen.client.Exception.UnknownStatusCodeException;
import app.sdkgen.client.Parser;
import app.sdkgen.client.TokenStoreInterface;
import com.fasterxml.jackson.core.type.TypeReference;
import org.apache.hc.client5.http.classic.methods.*;
import org.apache.hc.core5.http.ContentType;
import org.apache.hc.core5.http.io.entity.EntityUtils;
import org.apache.hc.core5.http.io.entity.StringEntity;
import org.apache.hc.core5.net.URIBuilder;

import java.io.IOException;
import java.net.URISyntaxException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Client extends ClientAbstract {
    public Client(String baseUrl, CredentialsInterface credentials) throws InvalidCredentialsException {
        super(baseUrl, credentials);
    }

    public MetaTag meta()
    {
        return new MetaTag(
            this.httpClient,
            this.objectMapper,
            this.parser
        );
    }

    public RecordsTag records()
    {
        return new RecordsTag(
            this.httpClient,
            this.objectMapper,
            this.parser
        );
    }

    public FieldsTag fields()
    {
        return new FieldsTag(
            this.httpClient,
            this.objectMapper,
            this.parser
        );
    }

    public TablesTag tables()
    {
        return new TablesTag(
            this.httpClient,
            this.objectMapper,
            this.parser
        );
    }

    public CommentsTag comments()
    {
        return new CommentsTag(
            this.httpClient,
            this.objectMapper,
            this.parser
        );
    }



    public static Client build(String token) throws InvalidCredentialsException
    {
        return new Client("https://api.airtable.com/", new HttpBearer(token));
    }
}
