/**
 * Error automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.airtable;

import com.fasterxml.jackson.annotation.*;

public class Error {
    private ErrorDetails error;

    @JsonSetter("error")
    public void setError(ErrorDetails error) {
        this.error = error;
    }

    @JsonGetter("error")
    public ErrorDetails getError() {
        return this.error;
    }
}

