/**
 * FieldOptions automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.airtable;

public class FieldOptions extends java.util.HashMap<String, Object> {
}

