/**
 * Record automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.airtable;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.Map;
public class Record {
    private String id;
    private String createdTime;
    private Map<String, Object> fields;
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }
    @JsonGetter("id")
    public String getId() {
        return this.id;
    }
    @JsonSetter("createdTime")
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }
    @JsonGetter("createdTime")
    public String getCreatedTime() {
        return this.createdTime;
    }
    @JsonSetter("fields")
    public void setFields(Map<String, Object> fields) {
        this.fields = fields;
    }
    @JsonGetter("fields")
    public Map<String, Object> getFields() {
        return this.fields;
    }
}
