/**
 * RecordCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.airtable;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class RecordCollection {
    private String offset;
    private List<Record> records;
    @JsonSetter("offset")
    public void setOffset(String offset) {
        this.offset = offset;
    }
    @JsonGetter("offset")
    public String getOffset() {
        return this.offset;
    }
    @JsonSetter("records")
    public void setRecords(List<Record> records) {
        this.records = records;
    }
    @JsonGetter("records")
    public List<Record> getRecords() {
        return this.records;
    }
}
